# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local    
    hooks:      
      - id: unittests        
        name: run unit tests        
        entry: python3 -m unittest -v        
        language: python
        types: [python]
        additional_dependencies: []
        pass_filenames: false        
