services:
  app:
    build: .
    container_name: fast-api-learning
    command: uvicorn main:app --host 127.0.0.0 --port 8000 --reload --reload-include *
    ports:
      - 8000:8000
    volumes:
      - .:/app